FROM eclipse-temurin:17-jdk-jammy AS base
WORKDIR /service
COPY gradle/ gradle
COPY gradlew build.gradle settings.gradle ./
RUN ./gradlew build -x test --no-daemon || return 0
COPY src src

FROM base AS build
RUN ./gradlew clean build -x test --no-daemon

FROM eclipse-temurin:17-jre-jammy
WORKDIR /service
COPY --from=build /service/build/libs/spring-petclinic-*.jar spring-petclinic.jar
CMD ["java", "-Dspring.profiles.active=postgres", "-jar", "/service/spring-petclinic.jar"]
