version: "2.2"

services:
  petclinic:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
